### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by inigo333** [liaojinxing/StarRatingView#5]
//I think you are missing something:
- (void)setRating:(CGFloat)rating 
  {
  _rating = rating; //This is what I believe is missing
  ....
  }

//Otherwise, I don't see how can I get the rating from your pod.

//Thanks

**Comment by liaojinxing** [comment]
Yes, you're right. Thanks!
I've fixed this bug at this commit:https://github.com/liaojinxing/StarRatingView/commit/e996714370a93c68f7d7d6a68fd2431db345370c

**Comment by inigo333** [comment]
No worries.
Thank you for the pod, indeed.
